name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install a modern version of GCC (v13)
      - name: Install GCC 13
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60

      # Set up CMake
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.18.4'

      # Set up dependencies (if any) using a package manager like apt-get
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake # valgrind clang-tidy

      # Create build directory
      - name: Create build directory
        run: cmake -S . -B build

      # Build the project
      - name: Build project
        run: cmake --build build

      # Run the tests
      - name: Run unit tests
        run: |
          cd build
          ctest -C Debug --output-on-failure